# orchestrator/state.py
#
# ─────────────────────────────────────────────────────────────────────────────
# IntelligenceOS — Unified State Definition
# ─────────────────────────────────────────────────────────────────────────────
#
# WHY ONE STATE FOR BOTH v1 AND v2?
# ──────────────────────────────────
# LangGraph passes the ENTIRE State dict between every agent.
# Every agent receives all fields — even ones it doesn't use.
#
# The engineering rule: new fields in IntelligenceOS use NotRequired[].
# This means:
#   - v1 agents (SearchAgent, ResearchAgent, PublisherAgent) are UNCHANGED
#     They don't need to know about watchlist or knowledge_graph
#   - v2 agents (WatchlistAgent, GraphAgent, etc.) read/write only their fields
#   - The State grows, but agents stay focused on their own slice
#
# When a field is NotRequired[], it simply isn't present in the dict
# for v1 pipeline runs. You check with state.get("watchlist", []).
#
# FIELD GROUPS:
#   v1 core      → always present (task, thread, final_status, etc.)
#   v2 watchlist → WatchlistAgent reads/writes
#   v2 graph     → GraphAgent reads/writes
#   v2 brief     → BriefingAgent reads/writes
#   v2 alert     → AlertAgent reads/writes
# ─────────────────────────────────────────────────────────────────────────────

from operator import add
from typing import Annotated, Dict, List, NotRequired, Optional, TypedDict


class PersonalAIState(TypedDict):

    # ─────────────────────────────────────────────────────────────────────────
    # v1 FIELDS — unchanged from PersonalAI v1
    # These are always present in every pipeline run (both v1 and v2).
    # ─────────────────────────────────────────────────────────────────────────

    task: str
    """The user's research query or the current watchlist topic being checked."""

    post_to_telegram: bool
    """Whether the final thread should be posted to Telegram."""

    search_queries: List[str]
    """3 targeted queries generated by SearchAgent from the task."""

    search_results: List[dict]
    """Raw results from Tavily: [{title, url, snippet}, ...]"""

    scraped_content: List[str]
    """Cleaned page text from successfully scraped URLs."""

    research_summary: str
    """LLM-synthesised findings from scraped content."""

    thread: List[str]
    """5 formatted Telegram posts (max 270 chars each)."""

    twitter_thread: NotRequired[List[str]]
    """Legacy alias for thread. Kept for backward compatibility."""

    final_status: str
    """Pipeline outcome: 'in_progress' | 'completed' | 'failed' | 'post_failed'"""

    messages: Annotated[List[dict], add]
    """Full message history. Annotated[..., add] means LangGraph appends
    (never replaces) — each agent's messages accumulate into one list."""

    error: Optional[str]
    """Error details if any agent failed. None means clean run."""

    current_agent: str
    """Name of the node currently executing. Used for debug tracking."""


    # ─────────────────────────────────────────────────────────────────────────
    # v2 FIELDS — IntelligenceOS additions
    #
    # All NotRequired[] — not present in v1 pipeline runs.
    # Access with state.get("field_name", default) — never state["field_name"].
    # ─────────────────────────────────────────────────────────────────────────

    # ── WatchlistAgent fields ─────────────────────────────────────────────────
    watchlist: NotRequired[List[str]]
    """Topics being monitored.
    Example: ["LangGraph updates", "MCP spec changes", "CrewAI releases"]
    Source: watchlist_topics table in SQLite.
    Written by: caller before invoking intelligence pipeline."""

    delta_events: NotRequired[List[dict]]
    """What changed since the last check for each watched topic.
    Each event: {
        "topic":       str,   # which topic triggered this
        "summary":     str,   # what changed (LLM-generated)
        "source_url":  str,   # URL of the changed content
        "detected_at": str,   # ISO 8601 timestamp
    }
    Written by: WatchlistAgent."""

    importance_scores: NotRequired[Dict[str, float]]
    """LLM-judged importance of each delta event (0.0 – 10.0).
    Key: topic name. Value: score.
    Example: {"LangGraph updates": 8.5, "MCP spec changes": 9.2}
    Written by: WatchlistAgent.
    Read by: AlertAgent (to decide if immediate alert is needed)."""

    last_checked: NotRequired[Dict[str, str]]
    """When each topic was last checked.
    Key: topic name. Value: ISO 8601 timestamp.
    Example: {"LangGraph updates": "2026-04-11T09:00:00"}
    Written by: WatchlistAgent after completing its checks."""

    # ── GraphAgent fields ─────────────────────────────────────────────────────
    knowledge_graph: NotRequired[dict]
    """NetworkX DiGraph serialised to JSON (node-link format).
    Use memory.graph_store.dict_to_graph() to reconstruct.
    Nodes: topics, concepts, people, companies.
    Edges: {type: "relates_to" | "contradicts" | "extends" | "is_part_of",
            weight: float, source_run_id: int}
    Written by: GraphAgent."""

    new_connections: NotRequired[List[dict]]
    """Surprising links found between previously separate research threads.
    Each connection: {
        "node_a":       str,  # first concept
        "node_b":       str,  # second concept
        "relationship": str,  # how they connect
        "why_notable":  str,  # LLM explanation of why this is interesting
    }
    Written by: GraphAgent.
    Read by: BriefingAgent (highlighted in morning brief)."""

    # ── BriefingAgent fields ──────────────────────────────────────────────────
    formatted_brief: NotRequired[str]
    """The complete morning brief as a formatted string.
    Rendered from Jinja2 template. Sections:
        - Executive summary
        - Key deltas (what changed overnight)
        - New connections (unexpected graph links)
        - Action items for you
        - Sources
    Written by: BriefingAgent.
    Read by: AlertAgent (for Telegram delivery)."""

    # ── AlertAgent fields ─────────────────────────────────────────────────────
    alert_sent: NotRequired[bool]
    """Whether an immediate high-importance alert was sent to Telegram.
    True  = at least one topic scored above the alert threshold (default: 7.0)
    False = all topics below threshold, only morning brief delivered.
    Written by: AlertAgent."""
